#!/usr/bin/env python3
"""Three-phase stator drive with the waveform generated IN THE FRONT END.

Supersedes the _OFFSET write loop in stator_epics_drive.py for anything faster
than ~0.1 Hz rotor. Measured 2026-08-28, why:

    Driving f_elec = 4 Hz through V{n}_OFFSET at 320 Hz writes produced a
    SQUARE WAVE, not a sine. Harmonics came out at 1/3, 1/5, 1/7 of the
    fundamental (12, 20, 28 Hz) -- textbook odd-harmonic square-wave series --
    THD 38.8%, phases 0/180/180 instead of 0/-120/-240, and amplitudes
    2324/1039/1272 against 2000 commanded. The DC pedestal was perfect
    (2002/2001/1997), which is the tell: static settings get through,
    time-varying ones do not.

    The front end samples EPICS settings on its slow cycle (~16 Hz), so at
    4 Hz there are only ~4 samples per cycle no matter how fast we write. The
    2026-08-24 run looked perfect only because 0.16 Hz gave ~100 samples per
    cycle. No write rate and no TRAMP value fixes this.

So the AC has to be generated by the front end. AWG does that: the daemon
computes the sinusoid at the 2048 Hz model rate. This is also exactly what
diaggui does -- DTT injects through AWG (Aaron's measure_actuator_gain_config
documents diag excitations failing on `awgSetChannel` at MAX_NUM_AWG=9), so the
smooth sine seen from diaggui and the one produced here are the same mechanism.
diag adds SineResponse's transfer-function machinery, which a drive does not
need.

THE ONE THING THAT MAKES AWG WORK HERE -- and the reason every previous attempt
on this front end failed:

    ** start must be in the FRONT END's clock frame, i.e.
       Y1:DAQ-DC0_GPS + lead, NOT awgbase.GPSnow(). **

awg.py:128 defaults start to `GPSnow() + 4*_EPOCH`. The front end runs FAST of
true GPS (+8376 s on 2026-08-28, +7630 on 08-21, +5836 on 06-03 -- it drifts,
so this script re-measures every run and never uses a stored value). A start
computed from GPSnow() therefore lands ~2.3 hours in the front end's past, the
excitation is already expired, and it silently never plays. No error is raised.
Verified both ways 2026-08-28: true-GPS frame -> nothing at OUTMON;
front-end frame -> 800 counts commanded, 742.8 measured.

Because all phases share ONE start value, their relative phase is set purely by
the `phase` argument -- which is all a rotating field needs. The absolute phase
only picks which detent the rotor lands in at t=0.

DC and AC are split across two records, which is what the m=8 torque channel
wants anyway (tau_m8 ~ V_dc * V_ac):

    V{n}_OFFSET  = D                  static, one write, slowness irrelevant
    V{n}_EXC     = A*cos(wt + d_n)    front end, 2048 Hz, smooth

Nothing touches hardware without --live.
"""

import argparse
import math
import sys
import time

import numpy as np

try:
    from epics import caget, caput
except ImportError:
    caget = caput = None

PREFIX = 'Y1:RDS-OUTS'
DAQ_GPS_PV = 'Y1:DAQ-DC0_GPS'
DRVON_PV = f'{PREFIX}_DRVON'

PHASE_ELECTRODES = (2, 4, 3)      # A, B, C -- confirmed 2026-08-24
PHASE_NAMES = ('A', 'B', 'C')
M_DRIVE = 8                       # rotor speed = f_elec / 8

SW1_INPUT_ON = 4
SW2_OUTPUT_ON = 1024

# The filter banks are FLAT -- Y1RDS.txt defines zero filter sections on
# OUTS_V1..V4 (the only filter in the file is a PID on PD). So no foton work is
# needed to get equal amplitudes and exact phases, and nothing in the bank can
# be blamed for a phase error. Re-check that file before assuming otherwise.

MAX_TOTAL_COUNTS = 12800.0        # V{n}_LIMIT, engaged -- read back live 08-28
VOLTS_PER_COUNT = 0.0134          # measured; linearity ABOVE 6400 is unverified


def gps_now_fe():
    """Front-end GPS. Re-measured every run: the offset drifts and has jumped
    forward erratically (5836 -> 7630 -> 8376 s between June and August)."""
    return caget(DAQ_GPS_PV)


def reclaim_slots(electrodes=(1, 2, 3, 4), quiet=True):
    """Force-release leaked AWG slots. CALL THIS BEFORE EVERY RUN.

    Found the hard way 2026-08-28: a drive would work about three times and then
    silently stop producing AC -- OUT_DQ rms 0.00, only the DC pedestal, and NO
    error raised anywhere. Three electrodes per run against MAX_NUM_AWG = 9 is
    exactly three runs.

    The cause is in awg.py. Excitation.stop() only frees the slot when wait=True:

        ret = awgbase.awgStopWaveform(self.slot, 0, 0)
        self.stopped = True
        if wait:
            self.clear()      # awgClearWaveforms -> awgRemoveChannel -> tpClearName

    So stop(wait=False) leaks the slot, and so does a process that dies before it
    reaches stop() at all. awg.awg_cleanup() does NOT help -- it only closes the
    client-side interfaces (awgbase.awg_cleanup + testpoint_cleanup) and never
    touches the server's per-channel slots.

    Reclaiming means re-acquiring the channel and running the release sequence by
    hand. awgSetChannel returns the EXISTING slot for a channel that is already
    allocated, so this works even when the process that leaked it is long gone.

    Two rules that follow, and both matter:
      * always stop with wait=True;
      * never leave a drive running in a backgrounded process -- when the client
        exits the excitation dies with it, while the _OFFSET pedestal persists.
        That combination (DC present, AC absent) is what a leaked/dead drive
        looks like, and it fooled us repeatedly.
    """
    import awgbase
    freed = []
    for n in electrodes:
        chan = f'{PREFIX}_V{n}_EXC'
        try:
            awgbase.tpRequestName(chan, -1, None, None)
            slot = awgbase.awgSetChannel(chan)
            if slot >= 0:
                awgbase.awgClearWaveforms(slot)
                awgbase.awgRemoveChannel(slot)
                freed.append(f'V{n}:{slot}')
            awgbase.tpClearName(chan)
        except Exception as err:
            if not quiet:
                print(f'  ! reclaim {chan}: {err}')
    if freed and not quiet:
        print('  reclaimed AWG slots: ' + ', '.join(freed))
    return freed


def ac_present(electrodes, thresh=100.0):
    """Is there actually AC at the electrodes right now?

    A commanded value proves nothing on this path: when the AWG slots are
    exhausted the excitation silently does not play, and the only symptom is
    that OUT_DQ carries the DC pedestal with rms 0.00 and no error anywhere.
    So check the output, not the command.

    Reads one second of the fast DAQ channels -- enough for a yes/no on AC
    presence, though far too short to measure a frequency (a 1 s buffer of a
    3 s period is a third of a cycle; that mistake produced several bogus
    numbers on 2026-08-28).
    """
    try:
        import nds2
        conn = nds2.connection('cymac1', 8088)
        for blk in conn.iterate([f'{PREFIX}_V{n}_OUT_DQ' for n in electrodes]):
            rms = [float(np.array(x.data, float).std()) for x in blk]
            return all(r > thresh for r in rms), rms
    except Exception as err:
        print(f'  ! could not check for AC ({err}); proceeding blind')
    return True, []


def snapshot(electrodes):
    state = {}
    for n in electrodes:
        b = f'{PREFIX}_V{n}'
        state[n] = {s: caget(f'{b}_{s}') for s in
                    ('GAIN', 'OFFSET', 'TRAMP', 'SW1R', 'SW2R')}
    return state


def restore(state, dry):
    if dry:
        return
    for n, s in state.items():
        b = f'{PREFIX}_V{n}'
        for key, pv in (('OFFSET', f'{b}_OFFSET'), ('GAIN', f'{b}_GAIN'),
                        ('TRAMP', f'{b}_TRAMP'), ('SW1R', f'{b}_SW1S'),
                        ('SW2R', f'{b}_SW2S')):
            if s[key] is not None:
                caput(pv, float(s[key]), wait=True, timeout=2.0)
    print('  module state restored.')


def setup(electrodes, state, dc, set_input, dry):
    """GAIN = 1 and the output switch on are required for _EXC to reach the DAC.

    The INPUT switch is deliberately left ALONE by default. Aaron's recipe turns
    it off (it blocks the normal input path while EXC still passes), and that is
    also what keeps LES off V1/V2 -- LES_PIT and LES_YAW are live and summed in
    ahead of those two modules. But EXC has been seen working here with the
    input ON (V4, 2026-08-28), and a test suggesting it is REQUIRED off was
    taken while AWG slots were exhausted and is not trustworthy. So: do not
    guess, leave the switches where the operator put them, and let the
    verification step below report any channel that produced nothing.
    """
    for n in electrodes:
        b = f'{PREFIX}_V{n}'
        writes = [(f'{b}_GAIN', 1.0), (f'{b}_OFFSET', float(dc))]
        sw1, sw2 = int(state[n]['SW1R']), int(state[n]['SW2R'])
        if not sw2 & SW2_OUTPUT_ON:
            writes.append((f'{b}_SW2S', float(sw2 | SW2_OUTPUT_ON)))
        if set_input == 'on' and not sw1 & SW1_INPUT_ON:
            writes.append((f'{b}_SW1S', float(sw1 | SW1_INPUT_ON)))
        elif set_input == 'off' and sw1 & SW1_INPUT_ON:
            writes.append((f'{b}_SW1S', float(sw1 & ~SW1_INPUT_ON)))
        for pv, v in writes:
            print(f'    {"[dry] " if dry else ""}{pv} <- {v:g}')
            if not dry:
                caput(pv, v, wait=True, timeout=2.0)


def build(electrodes, amp, f_elec, f_elec_end, duration, start_ns, reverse):
    """One Sine (or SweptSine) per phase, all sharing `start_ns`."""
    import awg
    # SIGN: awg's `phase` argument enters with the OPPOSITE sign to the
    # _OFFSET write path. Measured 2026-08-28: commanding 0/-120/-240 through
    # awg produced 0/+120/+240 at V2/V4/V3, while the 2026-08-24 _OFFSET run
    # given the identical commanded order produced 0/-120/-240. Same spacing,
    # opposite progression -- i.e. the field rotates the other way.
    #
    # This is exactly the trap flex_spec.md flags: a transposition still makes
    # a clean travelling wave, so the drive "works" and the error only surfaces
    # as a sign when the video loop closes. The phases below are therefore
    # NEGATED relative to the intuitive order, so that this script produces the
    # SAME field direction as the verified 08-24 run (phase decreasing with
    # increasing azimuth => field rotates CCW in board coordinates).
    #
    # Re-measure with --verify after any change here. The pass condition is
    # relative phases of -120 and -240 (equivalently -120 and +120), NOT +120
    # and +240.
    order = [0.0, 4 * math.pi / 3, 2 * math.pi / 3] if reverse else \
            [0.0, 2 * math.pi / 3, 4 * math.pi / 3]
    exc = []
    for n, ph in zip(electrodes, order):
        chan = f'{PREFIX}_V{n}_EXC'
        if f_elec_end is None or f_elec_end == f_elec:
            exc.append(awg.Sine(chan, ampl=amp, freq=f_elec, phase=ph,
                                start=start_ns, duration=duration))
        else:
            # phase2 carries the same offset so the 120 deg spacing is held at
            # both ends of the sweep. Whether it is held THROUGHOUT is the one
            # thing the source does not settle -- --verify measures it.
            exc.append(awg.SweptSine(chan, ampl1=amp, freq1=f_elec, phase1=ph,
                                     ampl2=amp, freq2=f_elec_end, phase2=ph,
                                     freqramp='linear', start=start_ns,
                                     sweeptime=duration))
    return exc


LES_CHANS = ['Y1:RDS-LES_PIT_OUT_DQ', 'Y1:RDS-LES_YAW_OUT_DQ']
LES_MON = ['Y1:RDS-LES_PIT_OUTMON', 'Y1:RDS-LES_YAW_OUTMON']


def park(electrodes, dc, amp, duration, window, dry):
    """Hold a STATIONARY m=8 detent and watch the libration bleed off.

    Why this exists (measured 2026-08-28): driving a rotating field at 0.04 Hz
    rotor / 6400+6400 counts took LES_YAW rms from 267 to 1433 counts -- the
    drive was PUMPING the rotor, not capturing it, with no line at the drive
    frequency. Capture bandwidth assumes starting from REST. A rotor whose
    libration already exceeds the 45 deg detent spacing slips through detents,
    and every slip feeds energy in. At 2.9e-7 mbar there is no gas damping and
    with the laser off there is no dissipation at all, so it only gets worse.

    A stationary field does not pump. It just holds, which is what lets the
    rotor shed energy into the detent. This is the one stator result that is
    already proven on this apparatus: 2026-08-21, 6400 counts DC on V2 alone
    collapsed the libration 2.6x (rms 22.5 -> 8.6) and held it for 180 s.

    No AWG here at all. A static m=8 pattern is just three fixed DC values,
    V_k = V_dc + V_ac*cos(delta_k) for delta = 0, -120, -240 -- and DC is the
    one thing the slow _OFFSET path does perfectly (the 4 Hz run's pedestal was
    exact to 0.1 counts even while its AC was a square wave).

    Progress is read from LES_*_OUTMON at ~10 Hz rather than NDS: the slow
    monitor is only 16 Hz but the libration is ~0.17 Hz, so it is far above
    Nyquist, and it has no archive lag to wait on.
    """
    order = [0.0, -2 * math.pi / 3, -4 * math.pi / 3]
    offsets = [dc + amp * math.cos(d) for d in order]
    print('\n  static m=8 detent (no AWG -- pure DC):')
    for name, n, v in zip(PHASE_NAMES, electrodes, offsets):
        flag = '  ! outside [0, LIMIT]' if not 0 <= v <= MAX_TOTAL_COUNTS else ''
        print(f'    {name} V{n}_OFFSET <- {v:8.1f} counts '
              f'({v * VOLTS_PER_COUNT:6.1f} V){flag}')
    if any(not 0 <= v <= MAX_TOTAL_COUNTS for v in offsets):
        print('  ! refusing: a phase would clip or go negative.')
        return 1
    if dry:
        print(f'\n  [dry] would hold this for {duration:.0f} s and report LES '
              f'rms every {window:.0f} s.')
        return 0

    for n, v in zip(electrodes, offsets):
        caput(f'{PREFIX}_V{n}_OFFSET', float(v), wait=True, timeout=2.0)
    print(f'\n  parked. Holding {duration:.0f} s, LES rms every {window:.0f} s.')
    print(f'  Falling rms = the rotor is settling into the detent.\n')
    print(f'  {"t":>6} {"PIT rms":>10} {"YAW rms":>10} {"YAW mean":>10}')
    t0 = time.time()
    first = None
    try:
        while time.time() - t0 < duration:
            buf = {pv: [] for pv in LES_MON}
            tw = time.time()
            while time.time() - tw < window:
                for pv in LES_MON:
                    v = caget(pv, timeout=1.0)
                    if v is not None:
                        buf[pv].append(v)
                time.sleep(0.1)
            p = np.array(buf[LES_MON[0]]) if buf[LES_MON[0]] else np.array([0.0])
            y = np.array(buf[LES_MON[1]]) if buf[LES_MON[1]] else np.array([0.0])
            if first is None:
                first = y.std()
            trend = f'   ({y.std() / first:.2f}x of start)' if first else ''
            print(f'  {time.time() - t0:6.0f} {p.std():10.2f} {y.std():10.2f} '
                  f'{y.mean():10.1f}{trend}')
    except KeyboardInterrupt:
        print('\n  interrupted.')
    return 0


def les_report(gps_start, span, f_rotor, label):
    """Rotor motion from the optical lever, as a LOCK detector.

    LES_PIT/LES_YAW are the optical-lever readouts at 1024 Hz -- far better
    than video for deciding whether the rotor captured, because it is
    quantitative and we can ask a specific question of it:

      * locked   -> periodic line at the commanded rotor frequency (or a
                    harmonic of it: the disk has 8- and 12-fold features, so
                    8x and 12x are the ones to expect)
      * not locked -> energy stays at the libration frequency (~0.2 Hz,
                    measured 0.17 Hz optical spring) and is not commensurate
                    with the drive

    Call it once BEFORE the drive and once during, and compare. An absolute rms
    means little; the change does.
    """
    import nds2
    try:
        conn = nds2.connection('cymac1', 8088)
        conn.set_parameter('ALLOW_DATA_ON_TAPE', '1')
        bufs = conn.fetch(int(gps_start), int(gps_start + span), LES_CHANS)
    except Exception as err:
        print(f'  LES fetch ({label}) failed: {err}')
        return
    print(f'\n  LES -- {label}  ({span:.0f} s from FE GPS {gps_start:.0f})')
    for buf in bufs:
        x = np.array(buf.data, float)
        fs = float(buf.channel.sample_rate)
        name = buf.channel.name.split('-')[1].replace('_OUT_DQ', '')
        ac = x - x.mean()
        X = np.abs(np.fft.rfft(ac * np.hanning(len(ac))))
        fr = np.fft.rfftfreq(len(ac), 1 / fs)
        band = (fr > 0.005) & (fr < 30.0)
        peak = fr[band][np.argmax(X[band])]
        line = ''
        for h, tag in ((1, '1x'), (8, '8x'), (12, '12x')):
            f0 = h * f_rotor
            if f0 < fr[-1]:
                k = np.argmin(abs(fr - f0))
                # local SNR against a neighbourhood, so a real line stands out
                lo, hi = max(0, k - 60), min(len(X), k + 60)
                nb = np.median(X[lo:hi]) or 1.0
                line += f'  {tag}({f0:.3f}Hz) SNR {X[k] / nb:5.1f}'
        print(f'    {name:8s} rms {x.std():8.2f}  mean {x.mean():9.1f}  '
              f'peak {peak:6.3f} Hz{line}')


def verify(electrodes, gps_start, span, f_elec, lag):
    """Fit each electrode's OUT_DQ and report amplitude / relative phase / THD.

    This is not optional garnish. A commanded value proves nothing here: the
    _OFFSET route reported perfect commanded numbers while emitting a square
    wave. Measure the output or do not believe it.
    """
    import nds2
    print(f'\n  waiting {lag:.0f} s for NDS frames...')
    time.sleep(lag)
    chans = [f'{PREFIX}_V{n}_OUT_DQ' for n in electrodes]
    data = {}
    for attempt in range(1, 5):
        try:
            conn = nds2.connection('cymac1', 8088)
            conn.set_parameter('ALLOW_DATA_ON_TAPE', '1')
            for buf in conn.fetch(int(gps_start), int(gps_start + span), chans):
                n = int(buf.channel.name.split('_V')[1].split('_')[0])
                data[n] = (np.array(buf.data, float),
                           float(buf.channel.sample_rate))
            break
        except Exception as err:
            print(f'  fetch attempt {attempt} failed ({err}); retry in 15 s')
            time.sleep(15)
    if not data:
        print(f'! could not fetch. Re-fetch by hand from FE GPS '
              f'{gps_start:.0f} for {span:.0f} s.')
        return

    print(f'\n  {"":4} {"amp":>9} {"dc":>9} {"phase":>10} {"rel":>10} '
          f'{"want":>8} {"THD2-5":>8}')
    ref = None
    want = (0.0, -120.0, -240.0)
    for name, n, w in zip(PHASE_NAMES, electrodes, want):
        if n not in data:
            print(f'  {name} V{n}: NO DATA')
            continue
        x, fs = data[n]
        t = np.arange(len(x)) / fs
        om = 2 * math.pi * f_elec
        M = np.column_stack([np.cos(om * t), np.sin(om * t), np.ones_like(t)])
        a, b, c = np.linalg.lstsq(M, x, rcond=None)[0]
        amp = math.hypot(a, b)
        ph = math.degrees(math.atan2(-b, a))
        if ref is None:
            ref = ph
        rel = (ph - ref + 180) % 360 - 180
        X = np.abs(np.fft.rfft((x - x.mean()) * np.hanning(len(x))))
        fr = np.fft.rfftfreq(len(x), 1 / fs)
        k0 = np.argmin(abs(fr - f_elec))
        thd = math.sqrt(sum((X[np.argmin(abs(fr - k * f_elec))] / X[k0]) ** 2
                            for k in range(2, 6)))
        flag = '' if amp > 1 else '   <- NOTHING CAME OUT'
        print(f'  {name} V{n} {amp:9.1f} {c:9.1f} {ph:+9.2f}d {rel:+9.2f}d '
              f'{w:+7.1f}d {100 * thd:7.2f}%{flag}')
    print('\n  For reference: the 08-24 _OFFSET run at 0.16 Hz gave THD 0.03%;\n'
          '  the same route at 4 Hz gave 38.8% (a square wave).')


def main():
    p = argparse.ArgumentParser(
        description='Front-end-generated three-phase stator drive (AWG).',
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--live', action='store_true')
    p.add_argument('-f', '--freq', type=float, default=0.02,
                   help='ROTOR frequency, Hz (f_elec = 8x this). Default 0.02. '
                        'Use --felec instead if you want to state the drive '
                        'frequency directly.')
    p.add_argument('--felec', type=float, default=None,
                   help='ELECTRICAL drive frequency, Hz. Overrides -f. '
                        'Rotor speed = this / 8, because the 24 sectors on a '
                        '15 deg pitch wired ABCABC repeat every 45 deg, so one '
                        'electrical cycle advances the travelling wave by an '
                        'eighth of a turn.')
    p.add_argument('--to', type=float, default=None, metavar='F',
                   help='sweep to this rotor frequency (Hz mech) over '
                        '--duration, phase-continuously, via awg.SweptSine. '
                        'Omit for a fixed-frequency hold.')
    p.add_argument('--amp', type=float, default=2000.0,
                   help='AC amplitude per phase, counts (default 2000)')
    p.add_argument('--dc', type=float, default=None,
                   help='DC pedestal per phase, counts (default = --amp, which '
                        'maximises V_dc*V_ac subject to dc+amp <= LIMIT)')
    p.add_argument('--duration', type=float, default=120.0)
    p.add_argument('--lead', type=float, default=8.0,
                   help='seconds between arming and the shared start (default '
                        '8). Must exceed the setup writes or the start time '
                        'passes before the excitation is armed.')
    p.add_argument('--reverse', action='store_true',
                   help='swap B and C to reverse rotation')
    p.add_argument('--reclaim', action='store_true',
                   help='force-release AWG slots before arming. OFF by default: '
                        'doing this in-process appeared to BREAK arming on '
                        '2026-08-28. If the drive is genuinely stuck, run '
                        'lab_utils/awg_reclaim.py as a separate process first, '
                        'then start a fresh drive -- that is what recovered it.')
    p.add_argument('--set-input', choices=('leave', 'on', 'off'),
                   default='leave', help='module INPUT switch (default leave)')
    p.add_argument('--park', action='store_true',
                   help='hold a STATIONARY m=8 detent instead of rotating, and '
                        'report LES rms so you can watch the libration damp. '
                        'Pure DC, no AWG. Do this before trying to spin a hot '
                        'rotor -- a rotating field pumps a rotor it cannot '
                        'catch (measured 2026-08-28: LES_YAW rms 267 -> 1433).')
    p.add_argument('--window', type=float, default=20.0,
                   help='LES averaging window for --park, s (default 20)')
    p.add_argument('--verify', action='store_true',
                   help='capture OUT_DQ afterwards and report amp/phase/THD')
    p.add_argument('--nds-lag', type=float, default=30.0)
    args = p.parse_args()

    dry = not args.live
    dc = args.dc if args.dc is not None else args.amp
    electrodes = list(PHASE_ELECTRODES)
    if args.felec is not None:
        args.freq = args.felec / M_DRIVE
    f_elec = M_DRIVE * args.freq
    f_elec_end = M_DRIVE * args.to if args.to is not None else None

    if dc + args.amp > MAX_TOTAL_COUNTS:
        print(f'! dc + amp = {dc + args.amp:.0f} exceeds the engaged filter-module '
              f'LIMIT of {MAX_TOTAL_COUNTS:.0f} counts; it would clip.')
        return 1

    print('DRY RUN -- pass --live to drive.\n' if dry else 'LIVE\n')
    print('=' * 72)
    for name, n in zip(PHASE_NAMES, electrodes):
        print(f'  phase {name}  V{n}: EXC {args.amp:.0f} cts AC, '
              f'OFFSET {dc:.0f} cts DC')
    if f_elec_end is None:
        print(f'  hold   f_elec {f_elec:.4f} Hz   rotor {args.freq:.4f} Hz')
    else:
        print(f'  sweep  f_elec {f_elec:.4f} -> {f_elec_end:.4f} Hz   '
              f'rotor {args.freq:.4f} -> {args.to:.4f} Hz over '
              f'{args.duration / 60:.1f} min')
    print(f'  peak {dc + args.amp:.0f} counts ~ '
          f'{(dc + args.amp) * VOLTS_PER_COUNT:.0f} V '
          f'(linearity above 6400 counts / 85 V is UNVERIFIED)')
    print('=' * 72)

    if caget is None:
        print('! pyepics not importable.')
        return 1
    import awg

    fe = gps_now_fe()
    print(f'\n  front-end GPS {fe:.0f}  (re-measured; the offset drifts)')
    if caget(DRVON_PV):
        print('  DRVON is ON -- the hardwired sin/cos fan-out would sum in.')
        if not dry:
            caput(DRVON_PV, 0.0, wait=True)
            print('  turned it off.')

    state = snapshot(electrodes)
    print('\n  before:')
    for n in electrodes:
        s = state[n]
        print(f'    V{n}: GAIN {s["GAIN"]:g}  OFFSET {s["OFFSET"]:g}  '
              f'SW1R {s["SW1R"]:.0f}  SW2R {s["SW2R"]:.0f}')

    print('\n  setup:')
    setup(electrodes, state, 0.0 if args.park else dc, args.set_input, dry)

    if args.park:
        try:
            return park(electrodes, dc, args.amp, args.duration, args.window, dry)
        finally:
            restore(state, dry)

    if dry:
        print(f'\n  [dry] would arm 3 excitations at FE GPS '
              f'{fe + args.lead:.0f} and run {args.duration:.0f} s.')
        return 0

    # NOT reclaimed automatically. Doing tpRequestName -> awgSetChannel ->
    # awgRemoveChannel -> tpClearName immediately before arming appeared to make
    # arming FAIL (2026-08-28): the script worked reliably before the reclaim was
    # added, and afterwards a run would fail its first attempt right after the
    # reclaim. What actually recovered a genuinely stuck AWG was running the
    # reclaim as a SEPARATE process and then starting a fresh drive.
    #
    # How to tell whether slots are really leaked: reclaim_slots() prints the
    # slot it finds per channel. DISTINCT slots (e.g. 13005/13006/13007/13008)
    # mean four real allocations are being held -- reclaiming will help. The
    # SAME slot for all four means nothing is allocated, so the failure is
    # something else and reclaiming will not fix it.
    if args.reclaim:
        freed = reclaim_slots(quiet=False)
        print('  (reclaim requested; if the slots printed above are all the '
              'same number,\n   nothing was actually leaked and this will not '
              'have helped)')
        time.sleep(3)

    capture_start = None
    exc = []
    try:
        # Arming is INTERMITTENT and the root cause is not understood (2026-08-28).
        # Observed: identical back-to-back runs, one armed on the retry and the
        # next failed twice. What reliably helps is the library's own release
        # path -- stop(wait=True) -> clear() -> awgClearWaveforms/RemoveChannel/
        # tpClearName -- run on the FAILED excitation objects, which is more
        # thorough than reclaim_slots()'s manual sequence. So each attempt tears
        # down properly and pauses before trying again, rather than hammering.
        for attempt in range(1, 9):
            start_ns = int((gps_now_fe() + args.lead) * 1e9)
            print(f'\n  shared start: FE GPS {start_ns / 1e9:.1f} '
                  f'(+{args.lead:.0f} s, front-end frame -- NOT awgbase.GPSnow())')
            exc = build(electrodes, args.amp, f_elec, f_elec_end, args.duration,
                        start_ns, args.reverse)
            for e in exc:
                e.start(ramptime=0, wait=False)
            capture_start = gps_now_fe() + args.lead + 5
            time.sleep(args.lead + 6)
            ok, rms = ac_present(electrodes)
            if ok:
                print(f'  AC confirmed at the electrodes '
                      f'(rms {", ".join(f"{r:.0f}" for r in rms)})')
                break
            print(f'  ! NO AC at the electrodes (rms '
                  f'{", ".join(f"{r:.1f}" for r in rms)}) -- the excitation did '
                  f'not play.')
            for e in exc:
                try:
                    e.stop(ramptime=0, wait=True)
                except Exception:
                    pass
            exc = []
            if attempt < 8:
                print(f'  attempt {attempt} failed; reclaiming and retrying '
                      f'({8 - attempt} left)...')
                reclaim_slots()
                time.sleep(4)
            else:
                print('  no AC after 8 attempts. Beyond slot exhaustion -- check '
                      'DRVON,\n  the output switch (SW2 bit 1024), and whether '
                      'another client (diaggui,\n  awggui, a stale python) holds '
                      'the EXC channels.')
                return 1
        print(f'  running {args.duration:.0f} s...')
        time.sleep(max(0.0, args.duration - 6))
    finally:
        for e in exc:
            try:
                # wait=True releases the AWG slot. wait=False leaks it, and
                # leaked slots hit MAX_NUM_AWG=9 and make later runs fail in
                # confusing ways (this bit us on 2026-08-28).
                e.stop(ramptime=0, wait=True)
            except Exception as err:
                print(f'  ! stop: {err}')
        try:
            awg.awg_cleanup()
        except Exception:
            pass
        restore(state, dry)

    if args.verify:
        span = max(20.0, args.duration - args.lead - 12)
        f_fit = f_elec if f_elec_end is None else (f_elec + f_elec_end) / 2
        verify(electrodes, capture_start, span, f_fit, args.nds_lag)
        # Baseline from BEFORE the drive, same length, so the comparison is
        # like-for-like. Already archived, so no extra waiting.
        les_report(fe - span - 10, span, f_fit / M_DRIVE, 'BEFORE drive')
        les_report(capture_start, span, f_fit / M_DRIVE, 'DURING drive')
    return 0


if __name__ == '__main__':
    sys.exit(main())
